### ISSUE TITLE
VoxelSniper + Tekkit?

### ISSUE THREAD

**Issue by RpTheHotrod** [TVPT/VoxelSniper#119]
What version of VoxelSniper would work with Tekkit Classic (if any)? I noticed using the latest version gives the usual "it's installed" but any attempt at using a vs command gives the "internal error occurred" error. 

I know typically everyone keeps everything up to date, but Tekkit is a fairly popular mod that relies on an older version of minecraft.

**Comment by z1haze** [comment]
wtf?

**Comment by gabizou** [comment]
> wtf?

Yes? Could you maybe elaborate your statement?

**Comment by z1haze** [comment]
I'm just surprised of the answer simple tekkit will not be supported. Why not I ask. There are a very large portion of players who enjoy modded minecraft as well, why not make it available for them. Most plugins crossover

**Comment by Deamon5550** [comment]
Are you able to read the date on this? This issue is from more than two years ago when this was purely a plugin for the Bukkit API, something which tekkit is not, has never been, and will never be compatible with.

skip forward two years and this is a different story as there are versions of VoxelSniper for minecraft forge, the compatibility of these builds with tekkit is another matter, but this is not the place to discuss this.
