### ISSUE TITLE
When will VoxelSniper 7 be finished?

### ISSUE THREAD

**Issue by DeadlyForest** [TVPT/VoxelSniper#282]
I have installed the latest stable build of VS on jenkins. I am on spigot and it seems that there are a lot of brushes missing. When is VS 7 going to be finished? I really would love to have a finished version on my 1.8 server! :)

**Comment by Deamon5550** [comment]
This is the most useless thing I have ever seen. Issues are for reporting bugs or requesting issues not bitching about a lack of progress on an open source project for which [the last released version](http://dev.bukkit.org/media/files/796/868/VoxelSniper-5.170.0-SNAPSHOT.jar) still works perfectly fine for the majority of users (spigot 1.8). If you want progress you can a) submit code yourself via pull requests, b) wait, or c) pay me to prioritize my time because otherwise the order that I prioritize my time is going to fall towards what I consider more important projects at this time (eg. sponge and work that I am paid for).

**Comment by DeadlyForest** [comment]
I am sorry, this was posted before I was aware that you are working on other things. I wasn't trying to complain or be rude, I was just unaware that you had halted work on this and was asking when the rewrite would be finished. Please don't be pissed simply because I was not aware and try to explain it to me next time.
