### ISSUE TITLE
Console Error on startup

### ISSUE THREAD

**Issue by bloggy** [TVPT/VoxelSniper#287]
Error in console on startup
http://pastebin.com/txPeBXkG

Running latest Paper Spigot 1.9.

**Comment by Deamon5550** [comment]
I'm going to guess that this error does not occur if VoxelSniper is the only plugin on the server. Because thats an error from metrics and it doesn't line up with the version of metrics included with VoxelSniper. Something else is injecting an older version of metrics to the classpath that is calling the old getOnlinePlayers method.

**Comment by bloggy** [comment]
It still occurs (latest spigot 1.9.2).
http://hastebin.com/qimiqosula.avrasm
It shows up from time to time. I have tested with less plugins installed as well.

**Comment by Deamon5550** [comment]
Not a bug in voxelsniper, find whatever has the old version of metrics in the classpath.
